### PR TITLE
[Manta] LTO for release and benchmarking binaries

### LINKED ISSUE #289: LTO optimization for binary generation
Related issue: https://github.com/paritytech/polkadot/issues/4311

Not sure whether it will occur in `polkadot-v0.9.13`.

### PR DESCRIPTION
**Pull request by ghzlatarev**
## Description

closes: #289

* Add link time optimization for manta release and benchmarking binaries `CARGO_PROFILE_RELEASE_LTO=true RUSTFLAGS="-C codegen-units=1"`
* On average 25 - 50 percent decrease in weight after the optimization
* Doubles the compilation time
* Decreases the binary size from 48361KB to 38284KB 

## Benchmarking Jobs

Without LTO - https://github.com/Manta-Network/Manta/actions/runs/1627848446
With LTO - https://github.com/Manta-Network/Manta/actions/runs/1627848281

Compilation time was increased by 30 minutes from half hour to an hour.

### pallet-balances (before vs after):
* transfer() - 136_309_000 vs 87_921_000
* transfer_keep_alive() - 99_370_000 vs 64_661_000
* set_balance_creating() 52_630_000 vs 35_050_000

### pallet-collective (before vs after):
* execute() - 39_571_000 vs 26_335_000
* propose_proposed() - 71_509_000 vs 44_163_000
* vote() 64_624_000 vs 48_205_000

### pallet-democracy (before vs after):
* propose() - 118_151_000 vs 86_491_000
* second() - 70_268_000 vs 48_933_000
* vote_new() 78_750_000 vs 56_050_000

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [x] Targeted PR against correct branch (`manta` or `dolphin`) with right title (start with [Manta] or [Dolphin]),
- [x] Linked to Github issue with discussion and accepted design OR have an explanation in the PR that describes this work.
- [ ] Wrote unit tests.
- [x] Updated relevant documentation in the code.
- [x] Re-reviewed `Files changed` in the Github PR explorer.
- [ ] If runtime changes, need to update the version numbers properly:
   * `authoring_version`: The version of the authorship interface. An authoring node will not attempt to author blocks unless this is equal to its native runtime.
   * `spec_version`: The version of the runtime specification. A full node will not attempt to use its native runtime in substitute for the on-chain Wasm runtime unless all of spec_name, spec_version, and authoring_version are the same between Wasm and native.
   * `impl_version`: The version of the implementation of the specification. Nodes are free to ignore this; it serves only as an indication that the code is different; as long as the other two versions are the same then while the actual code may be different, it is nonetheless required to do the same thing. Non-consensus-breaking optimizations are about the only changes that could be made which would result in only the impl_version changing.
   * `transaction_version`: The version of the extrinsics interface. This number must be updated in the following circumstances: extrinsic parameters (number, order, or types) have been changed; extrinsics or pallets have been removed; or the pallet order in the construct_runtime! macro or extrinsic order in a pallet has been changed. If this number is updated, then the spec_version must also be updated 
- [ ] If needed, notify the committer this is a draft-release and a tag is needed after merging the PR.
- [x] Verify benchmarks & weights have been updated for any modified runtime logics
- [ ] If needed, bump `version` for every crate.
- [ ] If import a new pallet, choose a proper module index for it, and allow it in `BaseFilter`. Ensure **every** extrinsic works from front-end. If there's corresponding tool, ensure both work for each other.
- [ ] If needed, update our Javascript/Typescript APIs. These APIs are offcially used by exchanges or community developers.
- [ ] If we're going to issue a new release, freeze the code one week early(it depends, but usually it's one week), ensure we have enough time for related testing.

### CODE REVIEW

**Comment by Dengjianping** [comment]
What's the size of native binary if we enable LTO? Ideally, it should be smaller.

**Comment by ghzlatarev** [comment]
> What's the size of native binary if we enable LTO? Ideally, it should be smaller.

Indeed it is smaller - 48361KB vs 38284KB 
The binaries are actually uploaded in the benchmarking jobs if you wan to check it.

**Comment by Dengjianping** [comment]
Once this pr is merged, I'm going to do tps test, the tps should be higher.

**Review by Dengjianping — APPROVED** [review]
LGTM!

**Review by stechu — APPROVED** [review]

**Pull request merged**
