### PR TITLE
[Manta]update cargo lock for pallet-manta-pay

### PR DESCRIPTION
**Pull request by zhenfeizhang**

### CODE REVIEW

**Comment by zhenfeizhang** [comment]
Let's check if this fixes @xialovexia 's problem before merge

**Review by stechu — APPROVED** [review]
LGTM.

**Comment by stechu** [comment]
@zhenfeizhang  feel free to merge if the test passes.

**Comment by stechu** [comment]
oh, please use [Manta] prefix.

**Pull request merged**
