### PR TITLE
[Manta] Enable weights for pallet-manta-pay in the manta runtime node

### LINKED ISSUE #37: [Pallet-Manta-Pay] Configure extrinsic weights
* Integrate weights.rs file through the benchmarking process
* configure init_asset
* configure transfer_asset
* configure mint_private_asset
* configure private_transfer
* configure reclaim

* sanity check if the weight is not 0, by checking in the Polkadot.js UI

### PR DESCRIPTION
**Pull request by ghzlatarev**
Closes Manta-Network/pallet-manta-pay#37

* Enable weights for pallet-manta-pay in the manta runtime node

### CODE REVIEW

**Review by zhenfeizhang — APPROVED** [review]
LGTM.
I guess the CI failed because https://github.com/Manta-Network/pallet-manta-pay/pull/38/ is not merged yet?

**Comment by ghzlatarev** [comment]
@stechu @zhenfeizhang 

CI is going to fail with ```type WeightInfo = pallet_manta_pay::weights::SubstrateWeight<Runtime>;``` until the manta pay changes are merged into ```calamari```
You guys can still test locally if you modify the cargo.toml file.

**Comment by ghzlatarev** [comment]
> Closes [Manta-Network/pallet-manta-pay#37](https://github.com/Manta-Network/pallet-manta-pay/issues/37)
> 
> * Enable weights for pallet-manta-pay in the manta runtime node

**Comment by stechu** [comment]
looks good. As @zhenfeizhang  said, need to update `Cargo.lock` once `pallet-manta-pay` merged Manta-Network/pallet-manta-pay#38

**Comment by stechu** [comment]
@ghzlatarev the manta pay change has been merged.  This one is good to go after the CI passed.

**Review by stechu — APPROVED** [review]

**Pull request merged**
