### PR TITLE
[ready-to-merge] [manta] Update manta-pay dependency to fb53902d095849196f02e1337db4c88844398fd2

### LINKED ISSUE #84: Dependency Issues in Manta/Pallet-Manta-Pay/Manta-API/Manta-Types.

### PR DESCRIPTION
**Pull request by ghzlatarev**
closes #84 
* Run  ``cargo update -p pallet-manta-pay`` to update the dependency to commit https://github.com/Manta-Network/pallet-manta-pay/commit/fb53902d095849196f02e1337db4c88844398fd2
* Update CI to resolve nightly rust issues with ``parity-db``

### CODE REVIEW

**Comment by ghzlatarev** [comment]
Actually let's merge https://github.com/Manta-Network/pallet-manta-pay/pull/69 first.

**Review by zhenfeizhang — APPROVED** [review]
LGTM

**Comment by zhenfeizhang** [comment]
Is this one ready to merge? https://github.com/Manta-Network/pallet-manta-pay/pull/69 is already merged FYI

**Comment by ghzlatarev** [comment]
> Is this one ready to merge? [Manta-Network/pallet-manta-pay#69](https://github.com/Manta-Network/pallet-manta-pay/pull/69) is already merged FYI

Should be ready now. Let's just pass the CI just in case.

**Pull request merged**
