### PR TITLE
[Manta] Sync to latest commits for manta dependencies

### LINKED ISSUE #64: Test Coverage for all repos.
- [ ] manta-node
     * [ ] service.rs
     * [ ] rpc.rs
     * [x] command.rs
- [ ] manta-app
- [ ] manta-api
     * [ ] circuit.rs
     * [ ] payload.rs
     * [ ] gadget.rs
- [ ] manta-subxt
- [x] manta-crypto
     * [x] commitment.rs
     * [x] checksum.rs
     * [x] merkle_tree.rs
- [x] manta-error
     * [x] lib.rs
- [x] manta-asset
     * [x] processing.rs
     * [x] serdes.rs
     * [x] sanity.rs
- [ ] manta-data
     * [ ] default.rs
     * [ ] metadata.rs
     * [ ] sanity.rs
     * [ ] serdes.rs
     * [ ] zkp.rs
- [ ] manta-ledger
     * [ ] lib.rs

### PR DESCRIPTION
**Pull request by ghzlatarev**
closes Manta-Network/Manta#64
 
* Update manta dependencies to latest commits
* CI for Wasm benchmarking

### CODE REVIEW

**Comment by stechu** [comment]
@ghzlatarev  So the workflow for the Sync Commit is to review it first? and then you change back the `Cargo.toml`, and then merge it?

**Comment by ghzlatarev** [comment]
> @ghzlatarev So the workflow for the Sync Commit is to review it first? and then you change back the `Cargo.toml`, and then merge it?

Yep.

**Comment by ghzlatarev** [comment]
Yo, @stechu can we merge this ?

**Comment by ghzlatarev** [comment]
We should wait for https://github.com/Manta-Network/manta-api/pull/15 and update ``manta-api`` to get rid of std features in our runtime.

**Review by stechu — APPROVED** [review]

**Pull request merged**
