### PR TITLE
Zombienet migration

### LINKED ISSUE #680: TENTATIVE: Retire polkadot-launch for zombienet
manta-pc ( retired here #434 ) / polkadot-launch is a constant headache and now being deprecated https://github.com/paritytech/polkadot-launch/issues/189 with Shawn's blessing.

We should try to move our CI to this ASAP

### PR DESCRIPTION
**Pull request by Dengjianping**
## Description

Closes #680 

- [x] metadata diff
- [x] runtime upgrade
- [x] integration test - manta
- [x] integration test - calamari

---

Before we can approve this PR for merge, please make sure that **all** the following items have been checked off:
- [x] Connected to an issue with discussion and accepted design using zenhub "Connect issue" button below
- [x] Added **one** label out of the `L-` group to this PR
- [x] Added **one or more** labels from the `A-` and `C-` groups to this PR
- [x] Explicitly labelled `A-calamari` and/or `A-manta` if your changes are meant for/impact either of these (CI depends on it)
- [ ] Re-reviewed `Files changed` in the Github PR explorer.

Situational Notes:
- If adding functionality, write unit tests!
- If importing a new pallet, choose a proper module index for it, and allow it in `BaseFilter`. Ensure **every** extrinsic works from front-end. If there's corresponding tool, ensure both work for each other.
- If needed, update our Javascript/Typescript APIs. These APIs are officially used by exchanges or community developers.
- If modifying existing runtime storage items, make sure to implement storage migrations for the runtime and test them with `try-runtime`. This includes migrations inherited from upstream changes, and you can search the diffs for modifications of `#[pallet::storage]` items to check for any.

### CODE REVIEW

**Review by ferrell-code — APPROVED** [review]
maybe want to let #1242  merge first, lgtm

**Comment by Dengjianping** [comment]
> 

totally agreed

**Review by ghzlatarev — APPROVED** [review]
Greagt! Can you organize a meeting and demo this please.

**Comment by Dengjianping** [comment]
> Greagt! Can you organize a meeting and demo this please.

sure, I will

**Pull request merged**
