### PR TITLE
Remove timeout for check_tests pipeline

### PR DESCRIPTION
**Pull request by Dengjianping**
## Description

---

Before we can approve this PR for merge, please make sure that **all** the following items have been checked off:
- [ ] Connected to an issue with discussion and accepted design using zenhub "Connect issue" button below
- [x] Added **one** label out of the `L-` group to this PR
- [x] Added **one or more** labels from the `A-` and `C-` groups to this PR
- [x] Explicitly labelled `A-calamari` and/or `A-manta` if your changes are meant for/impact either of these (CI depends on it)
- [ ] Re-reviewed `Files changed` in the Github PR explorer.

Situational Notes:
- If adding functionality, write unit tests!
- If importing a new pallet, choose a proper module index for it, and allow it in `BaseFilter`. Ensure **every** extrinsic works from front-end. If there's corresponding tool, ensure both work for each other.
- If needed, update our Javascript/Typescript APIs. These APIs are officially used by exchanges or community developers.
- If modifying existing runtime storage items, make sure to implement storage migrations for the runtime and test them with `try-runtime`. This includes migrations inherited from upstream changes, and you can search the diffs for modifications of `#[pallet::storage]` items to check for any.

### CODE REVIEW

**Review by ghzlatarev — APPROVED** [review]

**Review by ferrell-code — COMMENTED** [review]
Can't we just make it a larger number like 300?

**Comment by Dengjianping** [comment]
> 

In last PR #1080, I had a issue about sscache, I thought I could extend the timeout to fix it, but failed. Finally, Georgi increased the size of cache, and I separated features to solve it. So now, it's unnecessary now.

**Review by ferrell-code — APPROVED** [review]

**Comment by Garandor** [comment]
> > 
> 
> In last PR #1080, I had a issue about sscache, I thought I could extend the timeout to fix it, but failed. Finally, Georgi increased the size of cache, and I separated features to solve it. So now, it's unnecessary now.

@Dengjianping If it's not necessary to remove the time limit, why did you merge it? I don't like the thought of having one or more perpetually stuck runners over time

**Comment by ghzlatarev** [comment]
> > > 
> > 
> > 
> > In last PR #1080, I had a issue about sscache, I thought I could extend the timeout to fix it, but failed. Finally, Georgi increased the size of cache, and I separated features to solve it. So now, it's unnecessary now.
> 
> @Dengjianping If it's not necessary to remove the time limit, why did you merge it? I don't like the thought of having one or more perpetually stuck runners over time

We didn't use the limit here and the amount that i added was just killing the jobs prematurely.
So that's why we removed it.
We can add a proper limit in a different PR, but it was out of scope for this one.

**Comment by Garandor** [comment]
> We didn't use the limit here and the amount that i added was just killing the jobs prematurely. So that's why we removed it. We can add a proper limit in a different PR, but it was out of scope for this one.

This statement is self-contradictory, if it killed stuff it was obviously "being used", no?
I do get that the tests run longer than 2 hrs so the limit is too low, i agree there.
Can we get this readded for the next release? @Dengjianping / @ghzlatarev could you propose a new PR?
It can be as simple as readding the deleted line with something like 300min timeout.

**Comment by ghzlatarev** [comment]
> > We didn't use the limit here and the amount that i added was just killing the jobs prematurely. So that's why we removed it. We can add a proper limit in a different PR, but it was out of scope for this one.
> 
> This statement is self-contradictory, if it killed stuff it was obviously "being used", no? I do get that the tests run longer than 2 hrs so the limit is too low, i agree there. Can we get this readded for the next release? @Dengjianping / @ghzlatarev could you propose a new PR? It can be as simple as readding the deleted line with something like 300min timeout.

I meant we didn't use a time limit in this workflow before the last commit which added the limit for an unrelated reason, which it didn't affect in the end. But yeah definitely a proper limit for maybe 2.5 -3 hours would be useful.

**Pull request merged**
