### PR TITLE
Fix release binary building

### LINKED ISSUE #1098: Update to latest sr-tool image when compatible
#1097 uses old version of sr-tool. Switch back when release will compile with latest sr-tool image.

Most likely will work when #1029 is merged

### LINKED ISSUE #1158: Building release binary with stable rust in publish-draft-release workflow can't startup a new chain
- [ ] Building release binary with stable rust in publish-draft-release workflow can't startup a new chain. It will fail with the 192 unknown opcode.
However upgrading and restarting or syncing from scratch an already running node doesn't have this issue.

- [ ] getting similar issue on runtime-upgrade workflow where the srtool build is failing

### PR DESCRIPTION
**Pull request by Dengjianping**
## Description

1. Bump srtool from 0.4 to 0.7.
2. Rollback stable rust to 1.69. I tried 1.71(just released last week), it has the same problem.

Closes #1098 #1158 

---

Before we can approve this PR for merge, please make sure that **all** the following items have been checked off:
- [x] Connected to an issue with discussion and accepted design using zenhub "Connect issue" button below
- [x] Added **one** label out of the `L-` group to this PR
- [x] Added **one or more** labels from the `A-` and `C-` groups to this PR
- [x] Explicitly labelled `A-calamari` and/or `A-manta` if your changes are meant for/impact either of these (CI depends on it)
- [ ] Re-reviewed `Files changed` in the Github PR explorer.

Situational Notes:
- If adding functionality, write unit tests!
- If importing a new pallet, choose a proper module index for it, and allow it in `BaseFilter`. Ensure **every** extrinsic works from front-end. If there's corresponding tool, ensure both work for each other.
- If needed, update our Javascript/Typescript APIs. These APIs are officially used by exchanges or community developers.
- If modifying existing runtime storage items, make sure to implement storage migrations for the runtime and test them with `try-runtime`. This includes migrations inherited from upstream changes, and you can search the diffs for modifications of `#[pallet::storage]` items to check for any.

### CODE REVIEW

**Comment by Dengjianping** [comment]
I did runtime upgrade with this [draft build](https://github.com/Manta-Network/Manta/releases/tag/untagged-b00ec27e72473bfde0c3), and started a whole new network, it worked.

**Review by ghzlatarev — COMMENTED** [review]
Nice, can you change it in the runtime-upgrade workflow as well

**Comment by ghzlatarev** [comment]
I guess also spawn an issue to change to 1.71 at some point (add to Pending pipeline)

**Comment by Dengjianping** [comment]
> Nice, can you change it in the runtime-upgrade workflow as well

I found this workflow doesn't need to build any binary.

**Comment by ghzlatarev** [comment]
> > Nice, can you change it in the runtime-upgrade workflow as well
> 
> I found this workflow doesn't need to build any binary.

Yeah it downloads a binary that the user provides but uses srtool for the runtimes.
There might be a different problem there but let's still update sr-tool.

**Review by ghzlatarev — APPROVED** [review]

**Review by ferrell-code — APPROVED** [review]
Cool we still should remember to periodically bump the sr tool to the latest version

**Pull request merged**
