### PR TITLE
Add manta docker image to publish

### PR DESCRIPTION
**Pull request by ferrell-code**
## Description

Publish manta images to docker hub on release relates #1239 

---

Before we can approve this PR for merge, please make sure that **all** the following items have been checked off:
- [x] Connected to an issue with discussion and accepted design using zenhub "Connect issue" button below
- [x] Added **one** label out of the `L-` group to this PR
- [x] Added **one or more** labels from the `A-` and `C-` groups to this PR
- [x] Explicitly labelled `A-calamari` and/or `A-manta` if your changes are meant for/impact either of these (CI depends on it)
- [x] Re-reviewed `Files changed` in the Github PR explorer.

Situational Notes:
- If adding functionality, write unit tests!
- If importing a new pallet, choose a proper module index for it, and allow it in `BaseFilter`. Ensure **every** extrinsic works from front-end. If there's corresponding tool, ensure both work for each other.
- If needed, update our Javascript/Typescript APIs. These APIs are officially used by exchanges or community developers.
- If modifying existing runtime storage items, make sure to implement storage migrations for the runtime and test them with `try-runtime`. This includes migrations inherited from upstream changes, and you can search the diffs for modifications of `#[pallet::storage]` items to check for any.

### CODE REVIEW

**Review by ghzlatarev — APPROVED** [review]

**Review by Apokalip — DISMISSED** [review]

**Comment by ghzlatarev** [comment]
@ferrell-code let's figure out the /latest image before we merge this.

**Comment by ferrell-code** [comment]
> @ferrell-code let's figure out the /latest image before we merge this.

It makes the image created by this action the latest tag too. Not fool proof but that is way action works for calamari.

https://github.com/Manta-Network/Manta/blob/2bdf9446efbd38bd54a2008b103e2cc4f4f12fe6/.github/workflows/docker.yml#L27

**Comment by ghzlatarev** [comment]
> > @ferrell-code let's figure out the /latest image before we merge this.
> 
> It makes the image created by this action the latest tag too. Not fool proof but that is way action works for calamari.
> 
> https://github.com/Manta-Network/Manta/blob/2bdf9446efbd38bd54a2008b103e2cc4f4f12fe6/.github/workflows/docker.yml#L27

oh yeah makes sense, I suppose can we put the `latest` in an if statement , so it only happens for the manta run ?

**Comment by ferrell-code** [comment]
> > > @ferrell-code let's figure out the /latest image before we merge this.
> > 
> > 
> > It makes the image created by this action the latest tag too. Not fool proof but that is way action works for calamari.
> > https://github.com/Manta-Network/Manta/blob/2bdf9446efbd38bd54a2008b103e2cc4f4f12fe6/.github/workflows/docker.yml#L27
> 
> oh yeah makes sense, I suppose can we put the `latest` in an if statement , so it only happens for the manta run ?

It creates separate images for calamari and manta. So there can be two "latest" tags

**Review by ghzlatarev — DISMISSED** [review]

**Review by anaye1997 — DISMISSED** [review]
✅ (cc @ryanlin-tech @grenade )

**Review by ghzlatarev — APPROVED** [review]

**Review by anaye1997 — APPROVED** [review]

**Pull request merged**
