### PR TITLE
Release v4.4.0-1

### PR DESCRIPTION
**Pull request by ghzlatarev**
## Description

* Bump chain-specs and update changelog
* bump transaction version due to https://github.com/Manta-Network/Manta/pull/1236
* Skip bumping client version
* Skip rebenchmarking as no substantial change to runtime
---

Before we can approve this PR for merge, please make sure that **all** the following items have been checked off:
- [x] Connected to an issue with discussion and accepted design using zenhub "Connect issue" button below
- [x] Added **one** label out of the `L-` group to this PR
- [x] Added **one or more** labels from the `A-` and `C-` groups to this PR
- [x] Explicitly labelled `A-calamari` and/or `A-manta` if your changes are meant for/impact either of these (CI depends on it)
- [x] Re-reviewed `Files changed` in the Github PR explorer.
- [x] Add `A-integration-test-checks` to run **start-integration-test-checks** (Required)
- [x] Add `A-benchmark-checks` to run **start-benchmark-check** (Required)
- [x] Add `A-unit-test-checks` to run **start-unit-test-checks** (Required)
- [x] Add `A-congestion-test-checks` to run **start-integration-test-checks** (Optional)

Situational Notes:
- If adding functionality, write unit tests!
- If importing a new pallet, choose a proper module index for it, and allow it in `BaseFilter`. Ensure **every** extrinsic works from front-end. If there's corresponding tool, ensure both work for each other.
- If needed, update our Javascript/Typescript APIs. These APIs are officially used by exchanges or community developers.
- If modifying existing runtime storage items, make sure to implement storage migrations for the runtime and test them with `try-runtime`. This includes migrations inherited from upstream changes, and you can search the diffs for modifications of `#[pallet::storage]` items to check for any.

### CODE REVIEW

**Review by ferrell-code — COMMENTED** [review]
should bump transaction version due to https://github.com/Manta-Network/Manta/pull/1236/

**Comment by ghzlatarev** [comment]
> should bump transaction version due to #1236

good catch, thanks

**Review by ferrell-code — APPROVED** [review]
not sure how we want to deal with changelog version checker maybe fix the tool itself, lgtm

**Comment by ghzlatarev** [comment]
> not sure how we want to deal with changelog version checker maybe fix the tool itself, lgtm

Don't want to spend time on it. It's because of the `-1`

**Review by Dengjianping — APPROVED** [review]

**Pull request merged**
