### PR TITLE
[Manta] bump pallet-manta-pay version

### PR DESCRIPTION
**Pull request by stechu**
Update `pallet-manta-pay` to the newest version.

### CODE REVIEW

**Comment by stechu** [comment]
There is a visible performance regression here:
Before:
```
Pallet: "pallet_manta_pay", Extrinsic: "private_transfer", Lowest values: [], Highest values: [], Steps: [], Repeat: 10
Median Slopes Analysis
========
-- Extrinsic Time --

Model:
Time ~=   107600
              µs

Reads = 5
Writes = 3
Min Squares Analysis
========
-- Extrinsic Time --

Model:
Time ~=   107600
              µs

Reads = 5
Writes = 3
```
After:
```
Pallet: "pallet_manta_pay", Extrinsic: "private_transfer", Lowest values: [], Highest values: [], Steps: [], Repeat: 10
Median Slopes Analysis
========
-- Extrinsic Time --

Model:
Time ~=   113400
              µs

Reads = 5
Writes = 3
Min Squares Analysis
========
-- Extrinsic Time --

Model:
Time ~=   113400
              µs

Reads = 5
Writes = 3
```
@zhenfeizhang  any thoughts? If this is a non-zkp performance regression, it is pretty significant actually.

**Comment by stechu** [comment]
PS: this is a release build. Will try to use the release automation pipeline, so please don't merge it through web-interface.

**Comment by zhenfeizhang** [comment]
prob random noise, mine on this branch
```
z@manta-ubuntu:~/Desktop/Manta$ target/release/manta benchmark --pallet pallet_manta_pay --extrinsic private_transfer --repeat 100 --execution=wasm --wasm-execution compiled
2021-05-25 18:24:50 💸 Chain does not have enough staking candidates to operate. Era Some(0).    
2021-05-25 18:24:50 💸 Chain does not have enough staking candidates to operate. Era Some(1).    
Pallet: "pallet_manta_pay", Extrinsic: "private_transfer", Lowest values: [], Highest values: [], Steps: [], Repeat: 100
Median Slopes Analysis
========
-- Extrinsic Time --

Model:
Time ~=   109000
              µs

Reads = 5
Writes = 3
Min Squares Analysis
========
-- Extrinsic Time --

Model:
Time ~=   109000
              µs

Reads = 5
Writes = 3
```

**Comment by stechu** [comment]
@zhenfeizhang  I ran 3 times (each before and after), after getting rid of the outliers, can observe the result consistently.

**Comment by stechu** [comment]
update: I increased the repeat to `100`, the updated data is:
Before:
```
Pallet: "pallet_manta_pay", Extrinsic: "private_transfer", Lowest values: [], Highest values: [], Steps: [], Repeat: 100
Median Slopes Analysis
========
-- Extrinsic Time --

Model:
Time ~=   102900
              µs

Reads = 5
Writes = 3
Min Squares Analysis
========
-- Extrinsic Time --

Model:
Time ~=   102900
              µs

Reads = 5
Writes = 3

```
After:
```
Pallet: "pallet_manta_pay", Extrinsic: "private_transfer", Lowest values: [], Highest values: [], Steps: [], Repeat: 100
Median Slopes Analysis
========
-- Extrinsic Time --

Model:
Time ~=   104700
              µs

Reads = 5
Writes = 3
Min Squares Analysis
========
-- Extrinsic Time --

Model:
Time ~=   104700
              µs

Reads = 5
Writes = 3
```
I think we roughly have around `2ms` performance regression here. (again, it is not a big deal if that is due to ZKP, but it is a big deal if it is due to non-zkp code).

**Comment by stechu** [comment]
@zhenfeizhang  I think we should green light this for now? 1 - 2% regression is acceptable given the current state of the code.

**Comment by zhenfeizhang** [comment]
tracked done the changes here:
https://github.com/Manta-Network/pallet-manta-pay/compare/551210d5bb27f29f49971b90769295ec6d8b3590...b9e1cd2606f428c36c69630b32354734346d3205

there is no change on the extrinsic at all. 
The regression is either because of the noise, or you may have made consecutive benchmarks, and the second one needs to pull more data from the chain and causes some delay.

**Review by zhenfeizhang — APPROVED** [review]

**Pull request merged**
